# Generated by Django 4.2.1 on 2023-06-22 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('idObra', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id de Obra')),
                ('autor', models.CharField(max_length=20, verbose_name='Autor')),
                ('titulo', models.CharField(max_length=40, verbose_name='Titulo de obra')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_obras.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
